language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mechaximo/docker-project -f Dockerfile.dev .

script:
  - docker run -e CI=true mechaximo/docker-project npm run test
